In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.1


In [6]:
# Check MPS availability and build
is_mps_available = torch.backends.mps.is_available()
is_mps_built = torch.backends.mps.is_built()

print(f"MPS available: {is_mps_available}")
print(f"MPS built: {is_mps_built}")

# Test tensor operations on MPS if available
if is_mps_available:
    device = torch.device('mps')
    x = torch.randn(5, device=device)
    print("Tensor on MPS:", x)
else:
    print("MPS is not available.")

MPS available: True
MPS built: True
Tensor on MPS: tensor([-0.0345, -0.8145, -0.7001, -0.3488, -1.3099], device='mps:0')


## Introduction to Tensors
# Creating a Tensor

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.item()

7

In [12]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector.ndim

1

In [15]:
# Matrix

MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([3, 3])


In [16]:
# TENSOR
tensor = torch.tensor([[[1, 2, 3],
                         [4, 5, 6]],
                        [[7, 8, 9],
                         [10, 11, 12]],
                        [[13, 14, 15],
                         [16, 17, 18]]])
print(tensor.ndim)
print(tensor.shape)

3
torch.Size([3, 2, 3])


### Random Tensors

Random tensors are important because of the way that neural networks learn. They start with tensors full of random numbers and then adjust the numbers to better represent the data. 

In [17]:
#Create a random tensor with Pytorch

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8041, 0.0962, 0.1081, 0.6810],
        [0.9017, 0.0406, 0.7493, 0.4982],
        [0.1895, 0.8308, 0.2844, 0.8043]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create random tensor with similar shape to image tensor

image_tensor = torch.rand(size=(244, 244, 3)) # 3 channels for RGB
image_tensor.shape, image_tensor.ndim

(torch.Size([244, 244, 3]), 3)

## Zeros and Ones

In [20]:
# Create a tensor with zeros
zeros = torch.zeros(size=(3, 4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor with ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Create a range of tensors and tensors-like

In [22]:
# Use torch.range to create a tensor with a range of values
range_tensor = torch.arange(start=0, end=10, step=1)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Matrix Multiplication

In [39]:
A = torch.rand(3, 4)
B = torch.rand(3, 4)
print(A, B)

# Element-wise addition
C = A + B
print(C)

print(A*B)

tensor([[0.5062, 0.9907, 0.5472, 0.8706],
        [0.6437, 0.8616, 0.0518, 0.7971],
        [0.9041, 0.2593, 0.6537, 0.6611]]) tensor([[0.4385, 0.2953, 0.8034, 0.2791],
        [0.8700, 0.1835, 0.1035, 0.3195],
        [0.0986, 0.2883, 0.4179, 0.2257]])
tensor([[0.9447, 1.2860, 1.3506, 1.1497],
        [1.5136, 1.0451, 0.1553, 1.1166],
        [1.0026, 0.5476, 1.0716, 0.8868]])
tensor([[0.2220, 0.2925, 0.4396, 0.2430],
        [0.5600, 0.1581, 0.0054, 0.2547],
        [0.0891, 0.0748, 0.2732, 0.1492]])


In [40]:
# Matrix Multiplication
D = torch.mm(A, B.T)
D

tensor([[1.1971, 0.9571, 0.7607],
        [0.8007, 0.9782, 0.5134],
        [1.1826, 1.1130, 0.5863]])

In [42]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [52]:
print(A)
print(torch.argmax(A))

tensor([[0.5062, 0.9907, 0.5472, 0.8706],
        [0.6437, 0.8616, 0.0518, 0.7971],
        [0.9041, 0.2593, 0.6537, 0.6611]])
tensor(1)


In [53]:
A[1]

tensor([0.6437, 0.8616, 0.0518, 0.7971])

In [65]:
## Reshaping, stacking, squeezing, and unsqueezing tensors

# Reshape a tensor
x = torch.arange(1., 10., 1.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
## Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [67]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
# Changing z now changes x, as changing the view changes the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
# Stack tensors vertically 
# vstack dim = 0
# hstack dim = 1

x_stacked = torch.stack([x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([3, 9]))

In [73]:
# PyTorch and NumPy

# Usually, data comes in with NumPy array and needs to be changed to PyTorch tensor.

# Convert a NumPy array to a PyTorch tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))